import test from 'node:test';
import assert from 'node:assert/strict';
import {blankState,reduceState,validateState,type Command} from '../src/domain.ts';
import {factualReply,localIntent,parseCompanionResponse} from '../src/conversation.ts';
import {wavData,microphoneErrorMessage} from '../src/voice-recorder.ts';
import {defaultVoice,legacyDefaultVoice} from '../src/voice-config.ts';
const context={day:'2026-10-08',at:'2026-10-08T08:00:00Z',parent:true};
function setup(){return reduceState(blankState(),{type:'initialize',companion:'fox',name:'小狐狸',taskIds:['wash-hands'],rewardIds:['stickers'],credentials:{salt:'a'.repeat(32),pin:'b'.repeat(64),recovery:'c'.repeat(64)}},context);}
test('legacy version-one data gains disabled conversation and empty custom art',()=>{const old=JSON.parse(JSON.stringify(setup()));delete old.illustrations;delete old.settings.conversation;delete old.settings.voiceId;const s=validateState(old);assert.equal(s.settings.conversation,false);assert.deepEqual(s.illustrations,{});});

test('new default migrates the old built-in voice while retaining a custom voice',()=>{const s=setup();assert.equal(s.settings.voiceId,defaultVoice);s.settings.voiceId=legacyDefaultVoice;assert.equal(validateState(s).settings.voiceId,defaultVoice);assert.equal(s.settings.voiceId,legacyDefaultVoice);s.settings.voiceId='ttv-voice-personal';assert.equal(validateState(s).settings.voiceId,'ttv-voice-personal');});

test('new picture options persist through task, redemption snapshots and backup without publishing new templates',()=>{let s=setup();assert.equal(s.tasks.length,24);assert.equal(s.rewards.length,5);s=reduceState(s,{type:'saveTask',task:{...s.tasks[2],image:'read-alone'}},context);s=reduceState(s,{type:'claim',taskId:'wash-hands'},context);s=reduceState(s,{type:'submit',claimId:s.claims[0].id},context);s=reduceState(s,{type:'review',claimId:s.claims[0].id,approve:true},context);s=reduceState(s,{type:'saveReward',reward:{...s.rewards[0],price:3,image:'mystery-gift'}},context);s=reduceState(s,{type:'redeem',rewardId:'stickers',requestId:'gift-request'},context);const restored=validateState(JSON.parse(JSON.stringify(s)));assert.equal(restored.claims[0].image,'read-alone');assert.equal(restored.redemptions[0].image,'mystery-gift');assert.equal(restored.ledger[0].amount,3);});
test('task art and TTS save atomically; historical claims retain old image',()=>{let s=setup();const art='data:image/webp;base64,UklGRg==',audio='data:audio/mp3;base64,SUQz';s=reduceState(s,{type:'saveTask',task:{...s.tasks[2],image:'custom:first'},illustration:art,recording:audio},context);s=reduceState(s,{type:'claim',taskId:'wash-hands'},context);s=reduceState(s,{type:'saveTask',task:{...s.tasks[2],image:'custom:second'},illustration:art},context);assert.equal(s.claims[0].image,'custom:first');const restored=validateState(JSON.parse(JSON.stringify(s)));assert.equal(restored.illustrations['custom:first'],art);assert.equal(restored.recordings['wash-hands'],audio);});
test('unknown art and foreign data are rejected without mutating original state',()=>{const s=setup();const command:Command={type:'saveTask',task:{...s.tasks[2],image:'custom:new'},illustration:'https://example.com/image.webp'};assert.throws(()=>reduceState(s,command,context));assert.equal(s.tasks[2].image,'wash-hands');assert.deepEqual(s.illustrations,{});assert.throws(()=>reduceState(s,{type:'saveTask',task:{...s.tasks[2],image:'custom:missing'}},context));assert.throws(()=>reduceState(s,{type:'saveTask',task:s.tasks[2],recording:'data:audio/mp3;base64,SUQz'},{...context,parent:false}));});
test('conversation reports committed balance and active tasks without mutating state',()=>{let s=setup();const before=JSON.stringify(s);assert.equal(localIntent('今天要做什么任务'),'tasks');assert.match(factualReply(s,'tasks',context.day),/洗洗小手/);assert.match(factualReply(s,'balance'),/0颗/);assert.equal(JSON.stringify(s),before);s=reduceState(s,{type:'claim',taskId:'wash-hands'},context);s=reduceState(s,{type:'submit',claimId:s.claims[0].id},context);assert.match(factualReply(s,'tasks',context.day),/等家长确认/);assert.match(factualReply(s,'balance'),/0颗/);s=reduceState(s,{type:'review',claimId:s.claims[0].id,approve:true},context);assert.match(factualReply(s,'balance'),/3颗/);});
test('LLM output cannot invent a point award or request secret personal data',()=>{assert.equal(parseCompanionResponse('{"intent":"complete","reply":"给你100颗星星"}').intent,'complete');assert.doesNotMatch(parseCompanionResponse('{"intent":"chat","reply":"给你100颗星星"}').reply,/100/);assert.doesNotMatch(parseCompanionResponse('{"intent":"chat","reply":"告诉我你的电话"}').reply,/电话/);assert.equal(localIntent('我完成了，给我加分'),'complete');});
test('ASR recording is valid 16k mono PCM WAV and downsamples duration correctly',()=>{const samples=new Float32Array(48000).fill(.5),data=wavData(samples,48000),bytes=Buffer.from(data.split(',')[1],'base64');assert.equal(bytes.subarray(0,4).toString(),'RIFF');assert.equal(bytes.subarray(8,12).toString(),'WAVE');assert.equal(bytes.readUInt32LE(24),16000);assert.equal(bytes.readUInt16LE(22),1);assert.equal(bytes.readUInt16LE(34),16);assert.equal(bytes.length,32044);assert.equal(bytes.readInt16LE(44),16383);});

test('microphone startup errors explain permissions or unavailable hardware',()=>{assert.match(microphoneErrorMessage(new DOMException('Permission denied','NotAllowedError')),/权限/);assert.match(microphoneErrorMessage(new DOMException('No device','NotFoundError')),/没有找到/);assert.match(microphoneErrorMessage(new DOMException('Busy device','NotReadableError')),/其他录音应用/);assert.doesNotMatch(microphoneErrorMessage(new DOMException('Permission denied','NotAllowedError')),/网络|没听清/);});
test('claimed custom narration is immutable and shared between unchanged daily claims',()=>{let s=setup();const audio='data:audio/mp3;base64,SUQz';s=reduceState(s,{type:'recording',taskId:'wash-hands',data:audio},context);s=reduceState(s,{type:'claim',taskId:'wash-hands'},context);s=reduceState(s,{type:'claim',taskId:'wash-hands'},{...context,day:'2026-10-09'});assert.equal(s.claims[0].recordingId,s.claims[1].recordingId);assert.equal(Object.keys(s.voiceAssets).length,1);s=reduceState(s,{type:'recording',taskId:'wash-hands',data:'data:audio/mp3;base64,QVVESU8='},context);assert.equal(s.voiceAssets[s.claims[0].recordingId!],audio);});
